import {mkdir,cp,readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {validateJourneys} from '../01_shared_helpers/journey_schema.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
await mkdir(path.join(root,'dist/data'),{recursive:true});
await cp(path.join(root,'scripts/02_web_app'),path.join(root,'dist'),{recursive:true});
await cp(path.join(root,'scripts/01_shared_helpers/flight_math.mjs'),path.join(root,'dist/flight_math.mjs'));
await cp(path.join(root,'scripts/01_shared_helpers/time_and_light.mjs'),path.join(root,'dist/time_and_light.mjs'));
await cp(path.join(root,'scripts/01_shared_helpers/gap_details.mjs'),path.join(root,'dist/gap_details.mjs'));
for(const helper of ['individual_catalog.mjs','environment_math.mjs'])await cp(path.join(root,'scripts/01_shared_helpers',helper),path.join(root,'dist',helper));
await cp(path.join(root,'data/06_environment'),path.join(root,'dist/data/environment'),{recursive:true});
const catalog=JSON.parse(await readFile(path.join(root,'resources/configs/journey_catalog.json'),'utf8'));
const datasets=await Promise.all(catalog.datasets.map(async file=>JSON.parse(await readFile(path.join(root,file),'utf8'))));
const journeys=validateJourneys(datasets.flatMap(data=>data.journeys));
await writeFile(path.join(root,'dist/data/journeys.json'),JSON.stringify({schemaVersion:2,journeys}));
await writeFile(path.join(root,'dist/.nojekyll'),'');
let html=await readFile(path.join(root,'dist/index.html'),'utf8');
html=html.replace('<select id="speedSelect">','<select id="speedSelect"><option value="1">Real time</option><option value="10">10× speed</option>').replace('<option value="60">','<option value="60" selected>').replace('value="300" selected','value="300"');
await writeFile(path.join(root,'dist/index.html'),html);
console.log('Migration Lens static app built.');
